### ISSUE TITLE
Terragrunt fails to pass Var if type is not enforced

### ISSUE THREAD

**Issue by rsilva-rs** [kumarvna/terraform-azurerm-mssql-db#13]
## Issue:
When a Resource Group is not created within the module it is thrown the error message:
```yaml
Error: "resource_group_name" cannot be blank

  on main.tf line 90, in resource "azurerm_sql_server" "primary":
  90:   resource_group_name          = local.resource_group_name

Error: "location" must not be empty

  on main.tf line 91, in resource "azurerm_sql_server" "primary":
  91:   location                     = local.location
```
 
## Var Values:
`create_resource_group = false`
`resource_group_name = any-name`
`location = some-location` 

## Suggested solution:
It is not allowed to push to existing or create new branches. Code change to make it work could be something like that:
```yaml
locals {
  resource_group_name                = var.create_resource_group == false ? var.resource_group_name : element(coalescelist(data.azurerm_resource_group.rgrp.*.name, azurerm_resource_group.rg.*.name, [""]), 0)
  location                           = var.create_resource_group == false ? var.location : element(coalescelist(data.azurerm_resource_group.rgrp.*.location, azurerm_resource_group.rg.*.location, [""]), 0)
  if_threat_detection_policy_enabled = var.enable_threat_detection_policy ? [{}] : []
  #if_extended_auditing_policy_enabled = var.enable_extended_auditing_policy ? [{}] : []
}
```

**Comment by kumarvna** [comment]
This module supports creating a new resource group or using an existing one.  I have tested both scenarios thoroughly, and I am not able to reproduce the error.  Please check again and make sure the values for both `resource_group_name` and `location` are strings.  For more details, please check an examples folder in the repo. 

  resource_group_name = "rg-shared-westeurope-01"
  location                        = "westeurope"

**Comment by rsilva-rs** [comment]
Hey @kumarvna thanks for your prompt answer. You are right, on its own the module is working as intended. 
The thing is here we are using Terragrunt so when `create_resource_group` is passed to Terraform as `string` causing a false condition to `count = var.create_resource_group == false ? 1 : 0`. Pls, do you mind to enforce the typing for that?
```terraform
variable "create_resource_group" {
  description = "Whether to create resource group and use it for all networking resources"
  default     = true
  type        = bool
}
```

**Comment by kumarvna** [comment]
Interesting. If possible, please share the Terragrunt configuration and output to reproduce the error to work on a solution.

**Comment by rsilva-rs** [comment]
@kumarvna my initial comment has the config used and that error msg is the Terragrunt output. It worked when locally I enforced the typing `bool` for `create_resource_group`.

**Comment by rsilva-rs** [comment]
@kumarvna the initial comment has the same config used and that error msg is already the Terragrunt output. It worked when locally I enforced the typing bool for create_resource_group.

**Comment by kumarvna** [comment]
@rsilva-rs I have merged the change to the current release. Please check and let me know the result.

**Comment by rsilva-rs** [comment]
@kumarvna it is working. thank you!
